sudo: required
language: python

python:
  - "2.7"

env:
  - VERSION="8.0" LINT_CHECK="1"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
  - VERSION="8.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"
  - VERSION="8.0" UNIT_TEST="1" LINT_CHECK="0"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - sudo pip install phonenumbers py-Asterisk
  - hg clone http://bitbucket.org/anybox/web_action_request -b ${VERSION} ${HOME}/web_action_request
  - hg clone http://bitbucket.org/anybox/bus_enhanced ${HOME}/bus_enhanced

script:
  - travis_run_tests

after_success:
  coveralls
